export const SET_CHOSEN_NUMBER = "SET_CHOSEN_NUMBER";
export const SET_REQUEST = "SET_REQUEST";
export const SET_OUTPUT = "SET_OUTPUT";
export const SET_CURRENT_USER_NAME = "SET_CURRENT_USER_NAME";
export const SET_USERS_NAMES = "SET_USERS_NAMES";
